config/routes.rb
Rails.application.routes.draw do
  root 'doctors#index', as: 'doctors_index'
  resources :doctors
  resources :appointments

  get '/login' => 'users#new', as: 'login'
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  DOCTOR_MAXIMUM_AVAILABILITY = 7
  SUNDAY = 7

  has_many :appointments

  validates_presence_of :name, :address, :image, :city
  validates :name, format: NAME_REGEXP
  validates :address, format: /\A.{6,}/
  validates :image, format: /\A.+\.(gif|png|jpg|jpeg)\z/
  validate :validate_working_timestamps

  before_destroy :ensure_not_appointed

  def available_slots
    slots = {}
    return slots unless available

    DOCTOR_MAXIMUM_AVAILABILITY.times.each do |i|
      date = DateTime.now.beginning_of_day + i.days

      next if date.cwday == SUNDAY

      start_timestamp = time_of_day(date, start_time)
      end_timestamp = time_of_day(date, end_time)

      all_available_slots = slots_between(start_timestamp, end_timestamp)
                              .select! { |slot| slot_available?(slot) }

      slots[date] = all_available_slots unless all_available_slots.empty?
    end
    slots
  end

  def next_available_today
    today = DateTime.now.beginning_of_day

    today_slots = available_slots[today]

    return nil if today_slots.nil?
    today_slots[0].strftime("%l:%M %p")
  end

  private
  def time_of_day(date, time)
    date + time.seconds_since_midnight.seconds
  end

  def booked_slots
    appointments.all.map(&:date_time)
  end

  def slot_available?(slot)
    date = slot.beginning_of_day

    break_start_timestamp = time_of_day(date, break_start_time)
    break_end_timestamp = time_of_day(date, break_end_time)

    slot.future? && !booked_slots.include?(slot) && !slot.between_exclusive?(break_start_timestamp, break_end_timestamp)
  end

  def slots_between(start_time, end_time)
    start_time.step(end_time, 1.0 / 24).to_a
  end

  def ensure_not_appointed
    unless appointments.empty?
      errors.add(:appointments, "Appointment bookings already present")
      throw :abort
    end
  end

  def validate_working_timestamps
    unless break_end_time < end_time
      errors.add(:break_end_time, "Doctor's working timestamps are invalid")
      throw :abort
    end
    unless break_start_time < break_end_time
      errors.add(:break_start_time, "Doctor's working timestamps are invalid")
      throw :abort
    end
    unless start_time < break_start_time
      errors.add(:start_time, "Doctor's working timestamps are invalid")
      throw :abort
    end
  end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  # GET /doctors or /doctors.json
  def index
    @doctors = Doctor.all
  end
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/views/doctors/_doctor.html.erb
<div id="<%= dom_id doctor %>"
     class="doctor g-col-12 g-col-sm-6 bg-white rounded-3 border border-light">
  <div class="d-flex align-items-center column-gap-3">
    <%= image_tag doctor.image, alt: doctor.name, class: 'rounded-2' %>
    <div class="d-flex flex-column row-gap-lg-1">
      <p class="fw-semibold lh-sm fs-6 mb-0"><%= doctor.name %></p>
      <p class="fw-light fs-7 text-secondary mb-0"><%= doctor.address %></p>
      <p class="fw-light fs-7 text-secondary mb-0"><span class="fw-bold">City: </span><%= doctor.city %></p>
    </div>
  </div>
  <div class="d-flex align-items-center column-gap-sm-3 justify-content-between mt-1">
    <p class="text-secondary fs-7 fw-light lh-sm mb-0">
      <% if !doctor.available %>
        <span class="fw-semibold text-danger d-block my-2"><%= t('.not_available') %></span>
      <% elsif !doctor.next_available_today.nil? %>
        <span class="fw-semibold text-success"><%= t('.next_available') %></span>
        - <%= doctor.next_available_today %>
      <% else %>
        <span class="fw-semibold text-danger"><%= t('.not_available_today') %></span>
      <% end %>
    </p>
    <% if doctor.available %>
      <%= link_to t('.book_visit'), new_appointment_path(doctor_id: doctor),
                  class: "btn btn-primary rounded-2 fs-7 fw-semibold py-2 px-4" %>
    <% end %>
  </div>
</div>

app/views/doctors/index.html.erb
<% if notice %>
  <p class="alert alert-success mt-4 mb-0" role="alert">
    <%= notice %>
  </p>
<% end %>
<% if flash[:error] %>
  <p class="alert alert-danger mt-4 mb-0" role="alert">
    <%= flash[:error] %>
  </p>
<% end %>
<div id="doctors" class="mx-auto doctor-container d-flex flex-column d-sm-grid grid row-gap-3 row-gap-sm-4 column-gap-5">
  <div class="g-col-12">
    <div class="d-flex col-sm-5 align-items-center ps-0 gap-2 mt-5 mb-1">
      <%= image_tag 'icons/stethoscope', alt: 'Stethoscope', height: 31 %>
      <p class="my-0 fs-5"><%= t('.my_doctors') %></p>
    </div>
  </div>
  <% @doctors.each do |doctor| %>
    <%= render doctor %>
  <% end %>
</div>