config/routes.rb
Rails.application.routes.draw do
  root 'doctors#index', as: 'doctors_index'
  resources :doctors
  resources :appointments

  get '/login' => 'users#new', as: 'login'
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :doctor
  belongs_to :user

  validates_presence_of :date_time, :amount_inr, :currency_rates
  validates :amount_inr, numericality: { greater_than_or_equal_to: 0.01 }
  validate :future_date_time
  validate :date_time_is_valid_slot
  validate :currency_rates_format
  validate :doctor_to_be_available

  after_destroy :send_cancelled_mail

  APPOINTMENT_PRICE_INR = 500
  CANCEL_DEADLINE = 30.minutes
  COMPLETION_MAIL_DELIVERY = 2.hours

  private
  def future_date_time
    errors.add(:date_time,
               "Invalid appointment time") unless date_time&.after?(DateTime.now)
  end

  def date_time_is_valid_slot
    if date_time.present? && doctor.present?
      date = date_time.to_datetime.beginning_of_day
      slots = doctor.available_slots[date]

      errors.add(:date_time,
                 "Slot not available") unless !slots.nil? && date_time.in?(slots)
    end
  end

  def date_time_more_than_half_hour
    deadline = DateTime.now - CANCEL_DEADLINE

    errors.add(:date_time,
               "Cancellation window closed") unless date_time&.before?(deadline)
  end

  def currency_rates_format
    if currency_rates.present?
      User::CURRENCIES.each do |currency|
        errors.add(:currency_rates,
                   "Conversion for #{currency} is not present") if currency_rates[currency].nil?
      end
    end
  end

  def doctor_to_be_available
    if doctor.present?
      errors.add(:doctor, "Doctor not available") unless doctor.available
    end
  end

  def send_cancelled_mail
    AppointmentMailer.cancelled(self.as_json).deliver_later
  end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  include Authentication

  before_action :set_appointment, only: %i[ show destroy ]
  before_action :set_currency_rates, only: %i[ new create ]
  before_action :authenticate, only: %i[ index show destroy ]

  # GET /appointments or /appointments.json
  def index
    @user = get_session_user
    @appointments = @user.appointments
  end

  # GET /appointments/1 or /appointments/1.json
  def show
    respond_to do |format|
      if @appointment.nil?
        render_404
        return
      end
      format.html
      format.text do
        response.headers['Content-Type'] = 'text/plain'
        response.headers['Content-Disposition'] = "attachment; filename=receipt-#{@appointment.id}.txt"
      end
      format.csv do
        response.headers['Content-Type'] = 'text/csv'
        response.headers['Content-Disposition'] = "attachment; filename=receipt-#{@appointment.id}.csv"
      end
      format.pdf do
        render pdf: "receipt-#{@appointment.id}",
               page_size: 'A4',
               layout: "application",
               orientation: "Portrait",
               zoom: 1,
               dpi: 75,
               locals: { appointment: @appointment }
      end
    end
  end

  # GET /appointments/new
  def new
    @appointment = Appointment.new(doctor_id: params[:doctor_id])

    return redirect_to doctors_index_path,
                       flash: { error: t('.invalid_doctor_id') } if @appointment.doctor.nil?
    return redirect_to doctors_index_path,
                       flash: { error: t('.doctor_not_available') } unless @appointment.doctor.available

    @slots = @appointment.doctor.available_slots
    @uid = SecureRandom.uuid
    session_user = get_session_user
    session_user ? @appointment.user = session_user : @appointment.build_user
  end

  # POST /appointments or /appointments.json
  def create
    user = login_or_signup(appointment_params[:user])
    doctor = Doctor.find(appointment_params[:doctor_id])
    @uid = appointment_params[:uid]

    @appointment = Appointment.new(
      user: user,
      doctor: doctor,
      date_time: appointment_params[:date_time],
      amount_inr: Appointment::APPOINTMENT_PRICE_INR,
      currency_rates: @rates
    )

    if user.errors.any?
      @appointment.errors.merge!(user.errors)
      @appointment.build_user
    end

    respond_to do |format|
      if @appointment.errors.none? && @appointment.save
        format.turbo_stream { PaymentJob.perform_later(@appointment, @uid) }
      else
        @slots = doctor.available_slots
        format.html { render :new,
                             params: { doctor_id: appointment_params[:doctor_id] },
                             status: :unprocessable_entity }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1 or /appointments/1.json
  def destroy
    respond_to do |format|
      if @appointment.nil?
        render_404
        return
      end
      if (@appointment.date_time - DateTime.now) <= Appointment::CANCEL_DEADLINE
        format.html { redirect_to appointments_url, notice: t('.cancellation_windows_closed') }
      else
        @appointment.destroy!
        format.html { redirect_to appointments_url, notice: t('.appointment_cancelled') }
        format.json { head :no_content }
      end
    end
  end

  private

  def set_appointment
    @user = get_session_user
    return if @user.nil?
    @appointment = Appointment.find_by(id: params[:id], user_id: @user.id)
  end

  def set_currency_rates
    @rates = FixerApi.today_rates
    if @rates.nil?
      flash[:error] = t('.something_went_wrong')
      redirect_to doctors_index_path
    end
  end

  def appointment_params
    params.require(:appointment).permit(
      :uid,
      :date_time,
      :doctor_id,
      user: [:name, :email, :preferred_currency]
    )
  end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
  def print_appointment_price(rates, currency)
    amount_inr = Appointment::APPOINTMENT_PRICE_INR
    actual_price = convert_currency(amount_inr, rates, currency)
    "#{actual_price} #{currency}"
  end

  def parse_appointment_fees(appointment)
    currency = appointment.user.preferred_currency
    "#{currency} #{convert_currency(appointment.amount_inr, appointment.currency_rates, currency)}"
  end

  def parse_appointment_time(date_time, format)
    day_string = if date_time.today?
                   t('appointments.helpers.today')
                 elsif date_time.tomorrow?
                   t('appointments.helpers.tomorrow')
                 else
                   date_time.strftime("%A")
                 end
    date_string = date_time.day.ordinalize

    case format
    when 1
      "#{day_string}, #{date_string} #{date_time.strftime("%B, %l:%M %p")}"
    when 2
      "#{day_string}, #{date_string} #{date_time.strftime("%B")}"
    when 3
      date_time.strftime("%l:%M %p")
    when 4
      "#{date_string} #{date_time.strftime("%B, %l:%M %p")}"
    end
  end

  private
  def convert_currency(amount_inr, rates, currency)
    (amount_inr * rates[currency]).round(2)
  end
end

app/views/appointments/_appointment.html.erb
<div id="<%= dom_id appointment %>" class="g-col-12 g-col-md-6 fs-7">
  <div class="bg-white rounded-4 shadow p-2 h-100 d-flex flex-column">
    <div class="row my-3 justify-content-start">
      <div class="col-3">
        <%= image_tag appointment.doctor.image,
                      alt: appointment.doctor.name,
                      class: 'shadow-sm rounded-2',
                      height: 75 %>
      </div>
      <div class="col-8 d-flex flex-column justify-content-center">
        <p class="fs-6 fw-bold mb-0"><%= appointment.doctor.name %></p>
        <p class="text-secondary mb-0"><%= appointment.doctor.address %></p>
        <p class="text-secondary mb-0"><span class="fw-bold">City: </span><%= appointment.doctor.city %></p>
      </div>
    </div>
    <h6 class="col-12 mb-3 fs-7 text-secondary"><%= t('.your_consultation_details') %></h6>
    <div class="d-flex gap-3 mb-3 justify-content-between fs-7">
      <p
        class="flex-grow-1 pe-2 my-0 d-flex flex-row gap-1
        justify-content-start align-items-center fw-semibold border-end"
      >
        <%= image_tag 'icons/calendar_light', alt: "Calendar", size: 13 %>
        <%= parse_appointment_time(appointment.date_time, 2) %>
      </p>
      <p
        class="my-0 d-flex flex-row gap-3 justify-content-end align-items-center fw-semibold"
      >
        <%= image_tag 'icons/clock', alt: "Clock", size: 13 %>
        <%= parse_appointment_time(appointment.date_time, 3) %>
      </p>
    </div>
    <div class="flex-grow-1"></div>
    <div class="row mb-3 p-3 column-gap-3 justify-content-start text-secondary">
      <div class="col-12 p-0 fs-7 mb-2"><%= t('.download_your_invoice') %></div>
      <%= link_to 'CSV', appointment_path(appointment, format: :csv), class: 'col-3 btn btn-dark py-1 px-0' %>
      <%= link_to 'TXT', appointment_path(appointment, format: :txt), class: 'col-3 btn btn-dark py-1 px-0' %>
      <%= link_to 'PDF', appointment_path(appointment, format: :pdf), class: 'col-3 btn btn-dark py-1 px-0' %>
    </div>
    <div class="row mx-1 mb-2 px-3 py-2 rounded-3 justify-content-between bg-light">
      <p class="col-6 m-0 text-start"><%= t('.amount_paid') %></p>
      <p class="col-6 m-0 fw-bold text-primary text-end">
        <%= parse_appointment_fees(appointment) %>
      </p>
    </div>

    <div class="px-1">
      <%= button_to t('.cancel_appointment'),
                     appointment, method: :delete,
                     disabled: appointment.date_time - DateTime.now < Appointment::CANCEL_DEADLINE,
                     class: 'col-12 py-1 mb-1 rounded-3 fs-7 btn btn-outline-danger' %>
    </div>
  </div>
</div>

app/views/appointments/_form.html.erb
<%= form_with(model: appointment) do |form| %>
  <%= form.hidden_field :doctor_id, value: appointment.doctor.id %>
  <%= form.hidden_field :uid, value: @uid %>

  <div data-appointment-target="slotForm" class="slot-form mx-auto gap-3 d-none">
    <%= render partial: 'slot_form', locals: { form: form } %>
  </div>
  <div data-appointment-target="userForm" class="user-form mx-auto gap-3 d-none">
    <%= render partial: 'user_form', locals: { form: form } %>
  </div>
<% end %>

app/views/appointments/_payment_success.erb
<%= turbo_stream.replace('appointment_form') do %>
  <div class="payment-success mx-auto">
    <div class="card py-4 border-0 bg-white">
      <%= image_tag 'icons/congratulations',
                    alt: 'Congratulations',
                    class: 'card-img-top',
                    height: 45 %>
      <div class="card-body">
        <h4 class="card-title mb-4 text-success text-center fw-bold"><%= t('.congratulations') %></h4>
        <h6 class="h6 card-subtitle mb-2 text-center text-body-secondary"><%= t('.appointment_booked') %></h6>
        <p class="card-text fs-4 fw-bold text-primary text-center">
          <%= image_tag 'icons/calendar_light', alt: 'Calendar', size: 27 %>
          <span class="mx-2">
            <%= parse_time(appointment.date_time, 1) %>
        </span>
        </p>
        <p class="fs-6 text-center text-secondary"><%= t('.meeting_starts_in') %></p>
        <div class="countdown d-flex justify-content-center" data-controller="countdown">
          <div class="d-none" data-countdown-target="dateTime"><%= appointment.date_time %></div>

          <div class="days">
            <span data-countdown-target="day1">-</span>
            <span data-countdown-target="day0">-</span>
            <span class="label"><%= t('.days') %></span>
          </div>
          <span class="separator">:</span>
          <div class="hours">
            <span data-countdown-target="hour1">-</span>
            <span data-countdown-target="hour0">-</span>
            <span class="label"><%= t('.hours') %></span>
          </div>
          <span class="separator">:</span>
          <div class="minutes">
            <span data-countdown-target="minute1">-</span>
            <span data-countdown-target="minute0">-</span>
            <span class="label"><%= t('.mins') %></span>
          </div>
          <span class="separator">:</span>
          <div class="seconds">
            <span data-countdown-target="second1">-</span>
            <span data-countdown-target="second0">-</span>
            <span class="label"><%= t('.secs') %></span>
          </div>
        </div>
      </div>
    </div>
    <%= link_to appointments_path, class: 'btn btn-outline-primary my-4' do %>
      <%= t('.my_appointments') %> <%= image_tag 'icons/arrow', alt: 'right_arrow', width: 24, class: 'mx-2' %>
    <% end %>
  </div>
<% end %>

app/views/appointments/_payment_success.turbo_stream.erb
<%= turbo_stream.replace('appointment_payment') do %>
  <div class="payment-success mx-auto">
    <div class="card py-4 border-0 bg-white">
      <%= image_tag 'icons/congratulations',
                    alt: 'Congratulations',
                    class: 'card-img-top',
                    height: 45 %>
      <div class="card-body">
        <h4 class="card-title mb-4 text-success text-center fw-bold"><%= t('.congratulations') %></h4>
        <h6 class="card-subtitle mb-2 text-center text-body-secondary"><%= t('.appointment_booked') %></h6>
        <p class="card-text fs-4 fw-bold text-primary text-center">
          <%= image_tag 'icons/calendar_light', alt: 'Calendar', size: 27 %>
          <span class="mx-2">
            <%= parse_appointment_time(appointment.date_time, 1) %>
        </span>
        </p>
        <p class="fs-6 text-center text-secondary"><%= t('.meeting_starts_in') %></p>
        <div class="countdown d-flex justify-content-center" data-controller="countdown">
          <div class="d-none" data-countdown-target="dateTime"><%= appointment.date_time %></div>

          <div class="days">
            <span data-countdown-target="day1">-</span>
            <span data-countdown-target="day0">-</span>
            <span class="label"><%= t('.days') %></span>
          </div>
          <span class="separator">:</span>
          <div class="hours">
            <span data-countdown-target="hour1">-</span>
            <span data-countdown-target="hour0">-</span>
            <span class="label"><%= t('.hours') %></span>
          </div>
          <span class="separator">:</span>
          <div class="minutes">
            <span data-countdown-target="minute1">-</span>
            <span data-countdown-target="minute0">-</span>
            <span class="label"><%= t('.mins') %></span>
          </div>
          <span class="separator">:</span>
          <div class="seconds">
            <span data-countdown-target="second1">-</span>
            <span data-countdown-target="second0">-</span>
            <span class="label"><%= t('.secs') %></span>
          </div>
        </div>
      </div>
    </div>
    <%= link_to appointments_path, class: 'btn btn-outline-primary my-4' do %>
      <%= t('.my_appointments') %> <%= image_tag 'icons/arrow', alt: 'right_arrow', width: 24, class: 'mx-2' %>
    <% end %>
  </div>
<% end %>

app/views/appointments/_processing_payment.turbo_stream.erb
<%= turbo_stream.replace('appointment_form') do %>
  <div id="appointment_payment" class="vw-100 vh-100 position-fixed top-0 start-0
  d-flex align-items-center justify-content-center bg-black"
       style="--bs-bg-opacity: 0.5;">
    <div class="p-5 bg-info rounded-3 shadow-lg">
      <h1 class="fw-bold text-info-emphasis"><%= t('.processing_payment') %></h1>
    </div>
  </div>
<% end %>

app/views/appointments/_slot_form.html.erb
<section class="my-5">
  <h5 class="fw-semibold lh-lg mb-3">
    <%= image_tag 'icons/calendar_light', alt: 'Calendar', class: 'mx-2', size: 25 %>
    <%= t('.select_a_date') %>
  </h5>

  <div id="dateCarousel" class="carousel carousel-dark slide">
    <button class="carousel-control-prev" type="button" data-bs-target="#dateCarousel" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <div class="carousel-inner m-auto">
      <div role="tablist">
        <% @slots.keys.each_slice(3).each_with_index do |dates, i| %>
          <div class="carousel-item <%= 'active' if i == 0 %>">
            <% dates.each_with_index do |date, j| %>
              <div
                class="carousel-date w-100 mx-1 d-flex flex-column justify-content-center <%= 'active' if i + j == 0 %>"
                data-bs-toggle="tab"
                data-bs-target="#nav-<%= date.to_s.gsub(' ', '') %>"
                type="button"
                role="tab">
                <h5 class="d-block text-center">
                  <%= date.strftime("%a, %-d") %>
                </h5>
                <span class="d-block text-center text-secondary small"><%= date.strftime("%b") %></span>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
    <button class="carousel-control-next" type="button" data-bs-target="#dateCarousel" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
</section>

<section class="my-5">
  <% @slots.each_with_index do |(date, slots), i| %>
    <div class="tab-content">
      <div id="nav-<%= date.to_s.gsub(' ', '') %>" class="tab-pane fade <%= 'active show' if i == 0 %>" role="tabpanel">
        <h5 class="fw-semibold mb-0 mb-md-3">
          <%= image_tag 'icons/clock', alt: 'Clock', class: "mx-2", size: 25 %>
          <%= t('.select_a_time_for') %>
          <span class="text-primary">
            <%= date.strftime("%A, %-d %B") %>
          </span>
        </h5>
        <div class="grid gap-2 my-3 ms-5 ms-md-1 me-5 me-md-0">
          <% slots.each do |slot| %>
            <%= form.radio_button :date_time, slot, class: 'btn-check slot-button' %>
            <%= form.label "date_time_#{slot.to_s.gsub(/[:+]/, '').downcase}",
                           slot.strftime("%l:%M %p"),
                           class: 'g-col-4 btn btn-outline-primary px-1 rounded-3',
                           "data-action": 'click->appointment#enableBookAppointment' %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</section>

<section class="py-3 mt-auto">
  <small class="d-block m-auto text-center">
    <%= t('.high_demand_message') %>
  </small>
  <%= button_tag 'Book Appointment',
                 disabled: true,
                 type: 'button',
                 class: 'mt-3 btn btn-lg btn-primary text-white w-100 p-3 rounded-3',
                 'data-appointment-target': 'bookAppointment',
                 'data-action': 'click->appointment#activateUserForm' %>
</section>

app/views/appointments/_user_form.html.erb
<h3 class="text-center fw-bold mb-3"><%= t('.add_user_details') %></h3>
<%= form.fields_for :user, @appointment.user do |user_form| %>
  <div class="mb-3">
    <%= user_form.label :name, class: 'text-dark fw-semibold mb-1' %>
    <%= user_form.text_field :name,
                             placeholder: t('.enter_name'),
                             class: 'form-control form-control-lg bg-transparent fs-6 py-3 rounded-3',
                             required: true %>
  </div>

  <div class="mb-4">
    <%= user_form.label :email, class: 'd-block text-dark fw-semibold mb-1' %>
    <%= user_form.email_field :email,
                              placeholder: t('.enter_email'),
                              class: 'form-control form-control-lg bg-transparent fs-6 py-3 rounded-3',
                              required: true %>
  </div>

  <div class="grid gap-1 mb-4">
    <%= user_form.label t('.select_currency'), class: 'g-col-12 text-dark fw-semibold mb-1' %>
    <% User::CURRENCIES.each_with_index do |currency, i| %>
      <%= user_form.radio_button :preferred_currency,
                                 currency,
                                 class: 'btn-check',
                                 checked:
                                   currency == (@appointment.user&.preferred_currency || "INR"),
                                 "data-action": "appointment#convertCurrency",
                                 "data-appointment-text-param":
                                   print_appointment_price(
                                     @rates,
                                     currency
                                   )
      %>
      <%= user_form.label "preferred_currency_#{currency.downcase}",
                          currency,
                          class: 'btn fs-6 g-col-4' %>
    <% end %>
  </div>

  <div class="mb-3">
    <%= button_tag "Pay #{print_appointment_price(@rates,
                                                  @appointment.user&.preferred_currency || "INR")}",
                   type: 'submit',
                   class: 'mt-3 lh-sm btn btn-lg btn-primary w-100 px-3 py-2 rounded-2',
                   'data-appointment-target': 'payButton' %>
  </div>
<% end %>

app/views/appointments/index.html.erb
<% if notice %>
  <p class="alert alert-success mt-4 mb-0" role="alert">
    <%= notice %>
  </p>
<% end %>

<h3 class="fw-bold lh-base text-center my-4"><%= t('.my_appointments') %></h3>

<div id="appointments" class="grid appointments-container mx-auto gap-4 mb-3">
  <% @appointments.each do |appointment| %>
    <%= render appointment %>
  <% end %>
</div>

app/views/appointments/new.html.erb
<%= turbo_stream_from("appointment-#{@uid}") %>
<div data-controller="appointment" id="appointment_form">
  <% if @appointment.errors.any? %>
    <div class="text-danger mt-4">
      <p><%= pluralize(@appointment.errors.count, "error") %> <%= t('.appointment_error_message') %></p>
      <ul class="alert alert-danger">
        <% @appointment.errors.each do |error| %>
          <li class="ms-2"><%= error.type %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= render "form", appointment: @appointment %>
</div>

app/views/appointments/show.csv.erb
Appointment Id, Patient Name, Patient Email, Doctor Name, Doctor Address, Doctor City, Time of Meeting, Appointment Fees
"<%= @appointment.id %>", "<%= @appointment.user.name %>", "<%= @appointment.user.email %>", "<%= @appointment.doctor.name %>", "<%= @appointment.doctor.address %>", "<%= @appointment.doctor.city %>", "<%= parse_appointment_time(@appointment.date_time, 4) %>", "<%= parse_appointment_fees(@appointment) %>"

app/views/appointments/show.html.erb
<div class="appointment-page mx-auto mt-5">
  <h3 class="fw-bold lh-base text-center my-4"><%= t('.your_appointment_details') %></h3>
  <%= render @appointment %>
</div>

app/views/appointments/show.pdf.erb
<h1 class="text-center fw-bold">Medi App Receipt</h1>

<h1 class="fw-bold mt-5"><%= appointment.doctor.name %></h1>
<h2 class="fw-bold"><%= appointment.doctor.address %></h2>
<h3 class="fw-bold"><%= appointment.doctor.city %></h3>

<h1 class="mt-5 pt-5 mb-3">
  <span class="text-decoration-underline">Patient Name:</span>
  <%= appointment.user.name %>
</h1>
<h1 class="mt-5 pt-5 mb-3">
  <span class="text-decoration-underline">Patient Email:</span>
  <%= appointment.user.email %>
</h1>
<h1 class="mb-3">
  <span class="text-decoration-underline">Time of Meeting:</span>
  <%= parse_appointment_time(appointment.date_time, 4) %>
</h1>
<h1 class="mb-3">
  <span class="text-decoration-underline">Appointment Fees:</span>
  <%= parse_appointment_fees(appointment) %>
</h1>

app/views/appointments/show.text.erb
Medi App Receipt

Appointment Id: <%= @appointment.id %>
Patient Name: <%= @appointment.user.name %>
Patient Email: <%= @appointment.user.email %>
Doctor Name: <%= @appointment.doctor.name %>
Doctor Address: <%= @appointment.doctor.address %>
Doctor City: <%= @appointment.doctor.city %>
Time of Meeting: <%= parse_appointment_time(@appointment.date_time, 4) %>
Appointment Fees: <%= parse_appointment_fees(@appointment) %>"