config/routes.rb
Rails.application.routes.draw do
  root 'doctors#index', as: 'doctors_index'
  resources :doctors
  resources :appointments

  get '/login' => 'users#new', as: 'login'
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/layouts/_navbar.html.erb
<nav
  class="d-flex align-items-center justify-content-between justify-content-sm-start w-100 py-3 px-4"
>
  <%= link_to t('.title'), doctors_index_path,
              class: 'nav-brand fw-semibold lh-sm fs-5 mb-0 ms-sm-5 ps-sm-5 pe-4 text-decoration-none text-black' %>
  <%= link_to appointments_path,
              class: "text-decoration-none text-black #{current_page?(appointments_path) && 'filter-primary'}" do %>
    <div class="d-flex align-items-center ms-4 column-gap-2">
      <%= image_tag 'icons/calendar.svg', alt: 'calendar', class: 'object-fit-contain', width: 24 %>
      <span class="lh-base fs-6"><%= t('my_appointments') %></span>
    </div>
  <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= t('.title') %></title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application.bootstrap", "data-turbo-track": "reload" %>
  <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
</head>

<body>
<%= render 'layouts/navbar' %>
<div class="container">
  <%= yield %>
</div>
</body>
</html>

app/views/layouts/application.pdf.erb
<!DOCTYPE html>
<html lang="en-US">
  <head>
    <title>Medi App</title>
    <%= wicked_pdf_stylesheet_link_tag "pdf.bootstrap" %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>